# Generated by Django 5.2.8 on 2025-11-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("project_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "計画中"),
                            ("preparing", "実行準備中"),
                            ("running", "実行中"),
                            ("done", "完了"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=3)),
                ("assignee", models.CharField(blank=True, max_length=100)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_sheets",
                        to="checklists.checklist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
