# Generated by Django 5.2.8 on 2025-11-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processsheet",
            name="inspector",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="processsheet",
            name="lot_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="processsheet",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
