# Generated by Django 5.2.8 on 2025-11-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("number", "数値"),
                            ("text", "テキスト"),
                            ("select", "選択肢"),
                            ("boolean", "真偽"),
                            ("photo", "写真"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_items",
                        to="master.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
