# Generated by Django 5.2.8 on 2025-11-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkitem",
            name="allow_handwriting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="decimal_places",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="default_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="error_message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="max_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="min_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="reference_image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
